import type { Config } from 'tailwindcss';

const config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'type-display',
    'type-h2',
    'type-h3',
    'type-card-title',
    'type-lead',
    'type-body-lg',
    'type-body',
    'type-body-bold',
    'type-small',
    'type-eyebrow',
    'bg-surface-marketing',
    'bg-surface-marketing-dark',
    'bg-gradient-brand-subtle',
    'rounded-marketing-shell',
  ],
  theme: {
    fontSize: {},
    extend: {
      screens: {
        'auth-collapse': '1023.984px',
        'auth-compact': '368px',
        'account-collapse': '776.02px',
        'billing-collapse': '900.02px',
        'usage-collapse': '640.02px',
      },
      colors: {
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-ring': 'var(--accent-ring)',
        'promo-bg': 'var(--promo-bg)',
        'promo-bg-dark': 'var(--promo-bg-dark)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-zinc': 'var(--text-zinc)',
        'text-muted': 'var(--text-muted)',
        'text-strong': 'var(--text-strong)',
        'text-on-accent': 'var(--text-on-accent)',
        'text-body': 'var(--text-body)',
        'text-meta': 'var(--text-meta)',
        'text-code': 'var(--text-code)',
        'text-on-surface-inverse': 'var(--text-on-surface-inverse)',
        'text-on-surface-inverse-muted': 'var(--text-on-surface-inverse-muted)',
        'surface-page': 'var(--surface-page)',
        'surface-raised': 'var(--surface-raised)',
        'surface-sunken': 'var(--surface-sunken)',
        'surface-inverse': 'var(--surface-inverse)',
        'surface-marketing': 'var(--surface-marketing)',
        'surface-marketing-dark': 'var(--surface-marketing-dark)',
        'surface-card': 'var(--surface-card)',
        'surface-section': 'var(--surface-section)',
        'surface-field': 'var(--surface-field)',
        'border-subtle': 'var(--border-subtle)',
        'border-default': 'var(--border-default)',
        'border-card': 'var(--border-card)',
        'border-control': 'var(--border-control)',
        'focus-ring': 'var(--focus-ring)',
        'sev-critical': 'var(--sev-critical)',
        'sev-critical-bg': 'var(--sev-critical-bg)',
        'sev-high': 'var(--sev-high)',
        'sev-high-bg': 'var(--sev-high-bg)',
        'sev-medium': 'var(--sev-medium)',
        'sev-medium-bg': 'var(--sev-medium-bg)',
        'sev-low': 'var(--sev-low)',
        'sev-low-bg': 'var(--sev-low-bg)',
        'sev-info': 'var(--sev-info)',
        'sev-info-bg': 'var(--sev-info-bg)',
        'sev-resolved': 'var(--sev-resolved)',
        'sev-resolved-bg': 'var(--sev-resolved-bg)',
      },
      backgroundImage: {
        'gradient-cta': 'var(--gradient-cta)',
        'gradient-brand-subtle': 'var(--gradient-brand-subtle)',
        'wash-br': 'var(--wash-br)',
        'wash-tl': 'var(--wash-tl)',
      },
      borderWidth: {
        hairline: 'var(--border-width)',
      },
      outlineWidth: {
        hairline: 'var(--border-width)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        control: 'var(--radius-control)',
        card: 'var(--radius-card)',
        pill: 'var(--radius-pill)',
        'marketing-shell': 'var(--radius-marketing-shell)',
        'landing-frame': 'var(--radius-landing-frame)',
        'landing-canvas': 'var(--radius-landing-canvas)',
        'landing-scanner': 'var(--radius-landing-scanner)',
        'landing-nav': 'var(--radius-landing-nav)',
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        float: 'var(--shadow-float)',
        focus: 'var(--shadow-focus)',
      },
      spacing: {
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '3': 'var(--space-3)',
        '4': 'var(--space-4)',
        '5': 'var(--space-5)',
        '6': 'var(--space-6)',
        '8': 'var(--space-8)',
        '10': 'var(--space-10)',
        '12': 'var(--space-12)',
        '16': 'var(--space-16)',
        '20': 'var(--space-20)',
        '24': 'var(--space-24)',
        'landing-inset-x': 'var(--space-landing-inset-x)',
        'landing-inset-y': 'var(--space-landing-inset-y)',
        'landing-scanner-gap': 'var(--space-landing-scanner-gap)',
        'landing-control-x': 'var(--space-landing-control-x)',
        'landing-input-x': 'var(--space-landing-input-x)',
        'landing-core': 'var(--offset-landing-core-top)',
        'landing-copy-y': 'var(--offset-landing-copy-y)',
      },
      gridTemplateColumns: {
        'landing-hero': '1.05fr 0.95fr',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      maxWidth: {
        marketing: 'var(--container-marketing)',
        'landing-frame': 'var(--container-landing-frame)',
        'landing-hero': 'var(--container-landing-hero)',
        'landing-scanner': 'var(--width-landing-scanner)',
        'landing-copy': 'var(--width-landing-copy)',
        'public-shell': '70rem',
        'app-shell': 'var(--container-app)',
      },
      height: {
        control: 'var(--control-height)',
        'landing-header': 'var(--height-landing-header)',
        'landing-promo': 'var(--height-landing-promo)',
        'landing-control': 'var(--height-landing-control)',
        'landing-core': 'var(--size-landing-core)',
        hairline: 'var(--border-width)',
      },
      minHeight: {
        control: 'var(--control-height)',
        'landing-hero': 'var(--height-landing-hero)',
      },
      width: {
        control: 'var(--control-height)',
        'landing-core': 'var(--size-landing-core)',
      },
      fontSize: {
        'landing-title': 'var(--type-landing-title)',
        'landing-copy': 'var(--type-landing-copy)',
      },
      lineHeight: {
        'landing-title': 'var(--line-landing-title)',
        'landing-copy': 'var(--line-landing-copy)',
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
  plugins: [],
} satisfies Config;

export default config;
