import type { Config } from 'tailwindcss';

const config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'type-display',
    'type-h2',
    'type-h3',
    'type-card-title',
    'type-lead',
    'type-body-lg',
    'type-body',
    'type-body-bold',
    'type-small',
    'type-eyebrow',
    'bg-surface-marketing',
    'bg-surface-marketing-dark',
    'bg-gradient-brand-subtle',
    'rounded-marketing-shell',
  ],
  theme: {
    extend: {
      screens: {
        'marketing-mobile': '640px',
        'marketing-tablet': '768px',
        'marketing-menu': '900px',
        'marketing-narrow': '480px',
        'marketing-micro': '368px',
        'marketing-demo-compact': { max: '1024px' },
        'max-marketing-mobile': { max: '640px' },
        'max-marketing-tablet': { max: '768px' },
        'max-marketing-menu': { max: '900px' },
        'max-marketing-narrow': { max: '480px' },
        'max-marketing-micro': { max: '368px' },
        'max-marketing-demo-compact': { max: '1024px' },
        'max-pricing-tiers': { max: '720px' },
        'auth-collapse': '1023.984px',
        'auth-compact': '368px',
        'account-collapse': '776.02px',
        'billing-collapse': '900.02px',
        'usage-collapse': '640.02px',
      },
      colors: {
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-ring': 'var(--accent-ring)',
        'promo-bg': 'var(--promo-bg)',
        'promo-bg-dark': 'var(--promo-bg-dark)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-zinc': 'var(--text-zinc)',
        'text-muted': 'var(--text-muted)',
        'text-strong': 'var(--text-strong)',
        'text-on-accent': 'var(--text-on-accent)',
        'text-body': 'var(--text-body)',
        'text-meta': 'var(--text-meta)',
        'text-code': 'var(--text-code)',
        'text-on-surface-inverse': 'var(--text-on-surface-inverse)',
        'text-on-surface-inverse-muted': 'var(--text-on-surface-inverse-muted)',
        'surface-page': 'var(--surface-page)',
        'surface-raised': 'var(--surface-raised)',
        'surface-sunken': 'var(--surface-sunken)',
        'surface-inverse': 'var(--surface-inverse)',
        'surface-marketing': 'var(--surface-marketing)',
        'surface-marketing-dark': 'var(--surface-marketing-dark)',
        'surface-marketing-raised': 'var(--surface-marketing-raised)',
        'surface-hero': 'var(--surface-hero)',
        'surface-dark': 'var(--surface-dark)',
        'surface-ice': 'var(--surface-ice)',
        'marketing-primary': 'var(--text-marketing-primary)',
        'marketing-secondary': 'var(--text-marketing-secondary)',
        'marketing-muted': 'var(--text-marketing-muted)',
        'marketing-inverse': 'var(--text-marketing-inverse)',
        'marketing-inverse-muted': 'var(--text-marketing-inverse-muted)',
        'border-marketing': 'var(--border-marketing)',
        'border-marketing-inverse': 'var(--border-marketing-inverse)',
        'border-marketing-demo': 'var(--border-marketing-demo)',
        'border-marketing-finding': 'var(--border-marketing-finding)',
        'border-marketing-frame-divider': 'var(--border-marketing-frame-divider)',
        'border-marketing-pricing': 'var(--border-marketing-pricing)',
        'surface-marketing-tag': 'var(--surface-marketing-tag)',
        'surface-marketing-frame-dot': 'var(--surface-marketing-frame-dot)',
        'brand-electric': 'var(--brand-electric)',
        'surface-electric-soft': 'var(--surface-electric-soft)',
        'brand-electric-bright': 'var(--brand-electric-bright)',
        'brand-electric-pulse': 'var(--brand-electric-pulse)',
        'brand-marketing': 'var(--brand-marketing)',
        'brand-marketing-contrast': 'var(--brand-marketing-contrast)',
        'brand-highlight': 'var(--brand-highlight)',
        'surface-card': 'var(--surface-card)',
        'surface-section': 'var(--surface-section)',
        'surface-field': 'var(--surface-field)',
        'border-subtle': 'var(--border-subtle)',
        'border-default': 'var(--border-default)',
        'border-card': 'var(--border-card)',
        'border-control': 'var(--border-control)',
        'focus-ring': 'var(--focus-ring)',
        'sev-critical': 'var(--sev-critical)',
        'sev-critical-bg': 'var(--sev-critical-bg)',
        'sev-high': 'var(--sev-high)',
        'sev-high-bg': 'var(--sev-high-bg)',
        'sev-medium': 'var(--sev-medium)',
        'sev-medium-bg': 'var(--sev-medium-bg)',
        'sev-low': 'var(--sev-low)',
        'sev-low-bg': 'var(--sev-low-bg)',
        'sev-info': 'var(--sev-info)',
        'sev-info-bg': 'var(--sev-info-bg)',
        'sev-resolved': 'var(--sev-resolved)',
        'sev-resolved-bg': 'var(--sev-resolved-bg)',
      },
      backgroundImage: {
        'gradient-cta': 'var(--gradient-cta)',
        'gradient-brand-subtle': 'var(--gradient-brand-subtle)',
        'wash-br': 'var(--wash-br)',
        'wash-tl': 'var(--wash-tl)',
        'gradient-brand-marketing': 'var(--gradient-brand-marketing)',
        atmosphere: 'var(--gradient-atmosphere)',
        'marketing-stars': 'var(--gradient-marketing-stars)',
      },
      borderWidth: {
        hairline: 'var(--border-width)',
      },
      outlineWidth: {
        hairline: 'var(--border-width)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        control: 'var(--radius-control)',
        card: 'var(--radius-card)',
        pill: 'var(--radius-pill)',
        'landing-frame': 'var(--radius-landing-frame)',
        'landing-canvas': 'var(--radius-landing-canvas)',
        'landing-scanner': 'var(--radius-landing-scanner)',
        'landing-nav': 'var(--radius-landing-nav)',
        'marketing-shell': 'var(--radius-marketing-shell)',
        'marketing-card': 'var(--radius-marketing-card)',
        'marketing-demo': 'var(--radius-marketing-demo)',
        'marketing-demo-finding': 'var(--radius-marketing-demo-finding)',
        'marketing-explorer': 'var(--radius-marketing-explorer)',
        'marketing-pricing': 'var(--radius-marketing-pricing)',
        'marketing-price-highlight': 'var(--radius-marketing-price-highlight)',
        'marketing-principle': 'var(--radius-marketing-principle)',
        'marketing-workflow': 'var(--radius-marketing-workflow)',
        'marketing-readiness': 'var(--radius-marketing-readiness)',
        'marketing-repair': 'var(--radius-marketing-repair)',
        'marketing-pricing-table': 'var(--radius-marketing-pricing-table)',
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        float: 'var(--shadow-float)',
        focus: 'var(--shadow-focus)',
        'marketing-card': 'var(--shadow-marketing-card)',
        'marketing-float': 'var(--shadow-marketing-float)',
        'marketing-glow': 'var(--shadow-marketing-glow)',
        'marketing-explorer': 'var(--shadow-marketing-explorer)',
        'marketing-pricing': 'var(--shadow-marketing-pricing)',
      },
      spacing: {
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '3': 'var(--space-3)',
        '4': 'var(--space-4)',
        '5': 'var(--space-5)',
        '6': 'var(--space-6)',
        '8': 'var(--space-8)',
        '10': 'var(--space-10)',
        '12': 'var(--space-12)',
        '16': 'var(--space-16)',
        '20': 'var(--space-20)',
        '24': 'var(--space-24)',
        'landing-inset-x': 'var(--space-landing-inset-x)',
        'landing-inset-y': 'var(--space-landing-inset-y)',
        'landing-scanner-gap': 'var(--space-landing-scanner-gap)',
        'landing-control-x': 'var(--space-landing-control-x)',
        'landing-input-x': 'var(--space-landing-input-x)',
        'landing-core': 'var(--offset-landing-core-top)',
        'landing-copy-y': 'var(--offset-landing-copy-y)',
        'marketing-section': 'var(--space-marketing-section)',
        'marketing-section-tablet': 'var(--space-marketing-section-tablet)',
        'marketing-section-mobile': 'var(--space-marketing-section-mobile)',
        'marketing-report-heading-gap': 'var(--space-marketing-report-heading-gap)',
        'marketing-remediation-gap': 'var(--space-marketing-remediation-gap)',
        'marketing-remediation-tablet-gap': 'var(--space-marketing-remediation-tablet-gap)',
        'marketing-remediation-compact-gap': 'var(--space-marketing-remediation-compact-gap)',
        'marketing-remediation-mobile-gap': 'var(--space-marketing-remediation-mobile-gap)',
        'marketing-remediation-section': 'var(--space-marketing-remediation-section)',
        'marketing-faq-gap': 'var(--space-marketing-faq-gap)',
        'marketing-faq-gap-tablet': 'var(--space-marketing-faq-gap-tablet)',
        'marketing-faq-gap-mobile': 'var(--space-marketing-faq-gap-mobile)',
        'marketing-closing-top': 'var(--space-marketing-closing-top)',
        'marketing-closing-bottom': 'var(--space-marketing-closing-bottom)',
        'marketing-closing-top-mobile': 'var(--space-marketing-closing-top-mobile)',
        'marketing-closing-bottom-mobile': 'var(--space-marketing-closing-bottom-mobile)',
        'marketing-footer-top': 'var(--space-marketing-footer-top)',
        'marketing-demo-gap': 'var(--space-marketing-demo-gap)',
        'marketing-demo-padding': 'var(--space-marketing-demo-padding)',
        'marketing-demo-gap-compact': 'var(--space-marketing-demo-gap-compact)',
        'marketing-demo-padding-compact': 'var(--space-marketing-demo-padding-compact)',
        'marketing-demo-gap-mobile': 'var(--space-marketing-demo-gap-mobile)',
        'marketing-demo-padding-mobile': 'var(--space-marketing-demo-padding-mobile)',
        'marketing-demo-padding-mobile-x': 'var(--space-marketing-demo-padding-mobile-x)',
        'marketing-finding-padding': 'var(--space-marketing-finding-padding)',
        'marketing-principle-padding-y': 'var(--space-marketing-principle-padding-y)',
        'marketing-principle-padding-x': 'var(--space-marketing-principle-padding-x)',
        'marketing-workflow-padding-y': 'var(--space-marketing-workflow-padding-y)',
        'marketing-workflow-padding-x': 'var(--space-marketing-workflow-padding-x)',
        'marketing-area-explorer-padding': 'var(--space-marketing-area-explorer-padding)',
        'marketing-area-tab-x': 'var(--space-marketing-area-tab-x)',
        'marketing-area-tab-x-mobile': 'var(--space-marketing-area-tab-x-mobile)',
        'marketing-area-panel-top': 'var(--space-marketing-area-panel-top)',
        'marketing-area-panel-x': 'var(--space-marketing-area-panel-x)',
        'marketing-area-panel-bottom': 'var(--space-marketing-area-panel-bottom)',
        'marketing-area-panel-top-mobile': 'var(--space-marketing-area-panel-top-mobile)',
        'marketing-area-panel-x-mobile': 'var(--space-marketing-area-panel-x-mobile)',
        'marketing-cost-cell-mobile': 'var(--space-marketing-cost-cell-mobile)',
        'marketing-gutter': 'var(--space-marketing-gutter)',
        'marketing-mobile-gutter': 'var(--space-marketing-mobile-gutter)',
        'marketing-dot': 'var(--size-marketing-dot)',
        'marketing-hero-top': 'var(--space-marketing-hero-top)',
        'marketing-hero-top-mobile': 'var(--space-marketing-hero-top-mobile)',
        'marketing-stars-y': 'var(--inset-marketing-stars-top)',
        'marketing-mobile-stars-top': 'var(--inset-marketing-mobile-stars-top)',
        'marketing-mobile-stars-bottom': 'var(--inset-marketing-mobile-stars-bottom)',
        'marketing-form-gap': 'var(--space-marketing-form-gap)',
        'marketing-drawer-gutter': 'var(--space-marketing-drawer-gutter)',
      },
      gridTemplateColumns: {
        'landing-hero': '1.05fr 0.95fr',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
        marketing: ['var(--font-marketing)'],
      },
      maxWidth: {
        'public-marketing': 'var(--container-public-marketing)',
        'marketing-demo': 'var(--container-marketing-demo)',
        'marketing-header': 'var(--container-marketing-header)',
        'marketing-section': 'var(--container-marketing-section)',
        'marketing-copy': 'var(--container-marketing-copy)',
        'marketing-wide-copy': 'var(--container-marketing-wide-copy)',
        'marketing-body': 'var(--container-marketing-body)',
        'marketing-prompt': 'var(--container-marketing-prompt)',
        'marketing-pricing': 'var(--container-marketing-pricing)',
        'marketing-remediation': 'var(--container-marketing-remediation)',
        'marketing-evidence': 'var(--container-marketing-evidence)',
        'marketing-footer': 'var(--container-marketing-footer)',
        'marketing-area-explorer': 'var(--container-marketing-area-explorer)',
        marketing: 'var(--container-marketing)',
        'landing-frame': 'var(--container-landing-frame)',
        'landing-hero': 'var(--container-landing-hero)',
        'landing-scanner': 'var(--width-landing-scanner)',
        'landing-copy': 'var(--width-landing-copy)',
        'public-shell': '70rem',
        'app-shell': 'var(--container-app)',
      },
      height: {
        'landing-header-control': 'var(--size-landing-header-control)',
        control: 'var(--control-height)',
        'landing-header': 'var(--height-landing-header)',
        'landing-promo': 'var(--height-landing-promo)',
        'landing-control': 'var(--height-landing-control)',
        'marketing-framebar': 'var(--height-marketing-framebar)',
        'landing-core': 'var(--size-landing-core)',
        hairline: 'var(--border-width)',
      },
      minHeight: {
        control: 'var(--control-height)',
        'landing-hero': 'var(--height-landing-hero)',
        'marketing-tablet-hero': 'var(--height-marketing-tablet-hero)',
        'marketing-workflow-card': 'var(--height-marketing-workflow-card)',
        'marketing-evidence-card': 'var(--height-marketing-evidence-card)',
        'marketing-trust-card': 'var(--height-marketing-trust-card)',
        'marketing-area-tab': 'var(--height-marketing-area-tab)',
        'marketing-area-tab-mobile': 'var(--height-marketing-area-tab-mobile)',
        'marketing-area-panel': 'var(--height-marketing-area-panel)',
        'marketing-area-panel-mobile': 'var(--height-marketing-area-panel-mobile)',
        'marketing-faq-summary': 'var(--height-marketing-faq-summary)',
      },
      size: {
        'marketing-faq-icon': 'var(--size-marketing-faq-icon)',
        'landing-header-control': 'var(--size-landing-header-control)',
      },
      width: {
        'landing-header-control': 'var(--size-landing-header-control)',
        control: 'var(--control-height)',
        'landing-core': 'var(--size-landing-core)',
      },
      fontSize: {
        'landing-title': 'var(--type-landing-title)',
        'landing-copy': 'var(--type-landing-copy)',
        'marketing-display': 'var(--type-marketing-display)',
        'marketing-h2': 'var(--type-marketing-h2)',
        'marketing-body': 'var(--type-marketing-body)',
        'marketing-lead': 'var(--type-marketing-lead)',
        'marketing-description': 'var(--type-marketing-description)',
        'marketing-demo-heading': 'var(--type-marketing-demo-heading)',
        'marketing-principle-heading': 'var(--type-marketing-principle-heading)',
        'marketing-workflow-heading': 'var(--type-marketing-workflow-heading)',
        'marketing-card-heading': 'var(--type-marketing-card-heading)',
        'marketing-pricing-total': 'var(--type-marketing-pricing-total)',
        'marketing-trust-heading': 'var(--type-marketing-trust-heading)',
        'marketing-readiness-copy': 'var(--type-marketing-readiness-copy)',
        'marketing-closing-copy': 'var(--type-marketing-closing-copy)',
        'marketing-closing-copy-mobile': 'var(--type-marketing-closing-copy-mobile)',
        'marketing-area-heading': 'var(--type-marketing-area-heading)',
        'marketing-remediation-heading': 'var(--type-marketing-remediation-heading)',
        'marketing-faq-heading': 'var(--type-marketing-faq-heading)',
        'marketing-closing-heading': 'var(--type-marketing-closing-heading)',
        'marketing-label': 'var(--type-marketing-label)',
        'marketing-micro': 'var(--type-marketing-micro)',
        'marketing-stat': 'var(--type-marketing-stat)',
        'marketing-mobile-stat': 'var(--type-marketing-mobile-stat)',
        'marketing-mobile-copy': 'var(--type-marketing-mobile-copy)',
      },
      lineHeight: {
        'landing-title': 'var(--line-landing-title)',
        'landing-copy': 'var(--line-landing-copy)',
        'marketing-display': 'var(--line-marketing-display)',
        'marketing-h2': 'var(--line-marketing-h2)',
        'marketing-body': 'var(--line-marketing-body)',
        'marketing-lead': 'var(--line-marketing-lead)',
        'marketing-description': 'var(--line-marketing-description)',
        'marketing-demo-heading': 'var(--line-marketing-demo-heading)',
        'marketing-remediation-heading': 'var(--line-marketing-remediation-heading)',
        'marketing-faq-heading': 'var(--line-marketing-faq-heading)',
        'marketing-closing-heading': 'var(--line-marketing-closing-heading)',
        'marketing-stat': '1.1',
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
  plugins: [],
} satisfies Config;

export default config;
