/**
 * T248 — ported from design-system/ui_kits/strings.jsx (`window.WA_STRINGS`).
 *
 * Not assigned to any task on its own; folded into T248 because `theme.jsx`'s
 * own `useT()` reads exactly this table and returns the raw key when it is
 * absent. See PROGRESS.md and the T248 note in tasks.md.
 */

export type Lang = 'en' | 'ar';

const en = {
  promo: 'First audit free — 50 credits',
  nav_product: 'Product',
  nav_pricing: 'Pricing',
  nav_docs: 'Docs',
  nav_changelog: 'Changelog',
  signin: 'Sign in',
  start_free: 'Start free',
  hero_lead: 'Think your site is ready?',
  hero_accent: 'Prove it, then ship it.',
  hero_sub:
    'We audit performance, security, design, testing and search visibility — measured first, then explained. Then we re-verify every fix until the board is green.',
  url_ph: 'yoursite.com',
  hero_cta: 'Audit my site',
  stat_credits: 'free credits, no card',
  stat_areas: 'areas',
  stat_recheck: 'credits per re-check',
  diff_eyebrow: 'The difference',
  diff_h2: 'Everyone else sells you a report.',
  diff_lead:
    'We sell you the walk from red to green, and we verify each step. An issue turns green when a check passes, never when you say so.',
  diff_1t: 'Measured before inferred',
  diff_1d: 'Anything measurable is measured, not guessed. Every finding says which it is.',
  diff_2t: 'Green means verified',
  diff_2d: 'A narrow re-check costs 3 credits and seconds. It passes, or the issue stays red.',
  diff_3t: 'Degrade, never collapse',
  diff_3d: 'A failing capability degrades its area. You are told exactly what is missing.',
  proof_note:
    'A degraded area never reads as a pass. If we could not run a check, the report says so and you are not charged for it.',
  areas_eyebrow: 'Five areas',
  areas_h2: 'Every area reports independently.',
  a_perf: 'Performance',
  a_perf_d: 'Core Web Vitals, bundle composition, request patterns',
  a_sec: 'Security',
  a_sec_d: 'Headers, TLS, OWASP checks, leaked credentials, dependency CVEs',
  a_des: 'Design',
  a_des_d: 'Layout, hierarchy and contrast, against your stated brand intent',
  a_test: 'Testing',
  a_test_d: 'Functional flows driven in a real browser',
  a_seo: 'Search visibility',
  a_seo_d: 'Metadata, crawlability, content structure',
  areas_note:
    'Five areas cost 95 individually against 80 bundled. Complete coverage is always the cheapest route to complete coverage.',
  loop_eyebrow: 'The fix loop',
  loop_h2: 'Red to green, one check at a time.',
  loop_1t: 'Audit',
  loop_1d: 'Submit a URL, a repository, or an archive.',
  loop_2t: 'Fix',
  loop_2d: 'Copy the remediation prompt into your coding agent.',
  loop_3t: 'Re-check',
  loop_3d: '3 credits, seconds. It passes or it stays red.',
  loop_4t: 'Ship',
  loop_4d: 'A fresh full re-audit returns an explicit go or no-go.',
  cta_h2: 'Fifty credits. No card.',
  cta_lead: 'Enough to audit two or three areas of your real site and see real findings.',
  foot_tag:
    'Measured before inferred. Green means verified. You are never charged for our failures.',
  foot_product: 'Product',
  foot_pricing: 'Pricing',
  foot_company: 'Company',
  foot_dashboard: 'Dashboard',
  foot_admin: 'Admin console',
  foot_zero: 'zero third-party runtime requests',
  g_audits: 'Audits',
  g_account: 'Account',
  n_scan: 'New scan',
  n_progress: 'Live scan',
  n_report: 'Report',
  n_fixes: 'Fixes',
  n_readiness: 'Readiness',
  n_usage: 'Usage',
  n_billing: 'Billing and plans',
  n_profile: 'Profile',
  credits_left: 'credits left',
  top_up: 'Top up',
  scan_eyebrow: 'New scan',
  scan_title: 'What should we audit?',
  tab_url: 'URL',
  tab_repo: 'Repository',
  tab_archive: 'Archive',
  areas_label: 'Areas',
  quote: 'Quote',
  credits: 'credits',
  quote_bundled: 'Bundled — 15 credits below the individual total.',
  quote_note:
    'Nothing is charged until you accept this quote. If the platform fails mid-audit, the credits come back.',
  accept_run: 'Accept and run',
  drop_archive: 'Drop a .zip or .tar.gz',
  drop_note: 'Validated before extraction. Destroyed when the scan ends.',
  theme_dark: 'Dark',
  theme_light: 'Light',

  // T128 — auth pages.
  auth_signin_title: 'Sign in',
  auth_signin_lead: 'Your audits and fixes boards are where you left them.',
  auth_signin_foot_lead: 'No account?',
  auth_signin_foot_link: 'Start free',
  auth_signin_foot_tail: '— 50 credits, no card.',
  auth_email: 'Email',
  auth_password: 'Password',
  auth_forgot_link: 'Forgot?',
  auth_signin_submit: 'Sign in',
  auth_or: 'or',
  auth_github: 'Continue with GitHub',
  auth_register_title: 'Create an account',
  auth_register_lead:
    'Fifty credits, no card. Enough to audit two or three areas of your real site.',
  auth_register_foot_lead: 'Already have an account?',
  auth_register_foot_link: 'Sign in',
  auth_name: 'Name',
  auth_work_email: 'Work email',
  auth_password_hint: 'At least 12 characters',
  auth_register_note: 'We send one verification email. You cannot sign in until it is confirmed.',
  auth_register_submit: 'Create account',
  auth_verify_title: 'Check your email',
  auth_verify_lead: 'We sent a verification link to {email}. It expires in 24 hours.',
  auth_verify_foot_lead: 'Wrong address?',
  auth_verify_foot_link: 'Start again',
  auth_verify_resend: 'Resend the email',
  auth_verify_confirmed_title: 'Address confirmed',
  auth_verify_confirmed_lead: 'You can sign in now.',
  auth_verify_confirmed_submit: 'Sign in',
  auth_verify_invalid_title: 'This link is no longer valid',
  auth_verify_invalid_lead: 'It has already been used, or it expired.',
  auth_forgot_title: 'Reset your password',
  auth_forgot_lead: 'Enter the address on your account and we will send a single-use link.',
  auth_forgot_foot_link: 'Back to sign in',
  auth_forgot_submit: 'Send reset link',
  auth_forgot_sent_lead: 'If that address has an account, a reset link is on its way.',
  auth_reset_title: 'Choose a new password',
  auth_reset_lead: 'This link is single-use. Signing in again revokes every other session.',
  auth_reset_foot_link: 'Back to sign in',
  auth_new_password: 'New password',
  auth_confirm_password: 'Confirm new password',
  auth_repeat_it: 'Repeat it',
  auth_min_chars: '12 characters minimum',
  auth_reset_submit: 'Set password and sign in',
  auth_reset_done_title: 'Password changed',
  auth_reset_done_lead: 'All sessions were signed out. Sign in with your new password.',
  auth_error_generic: 'Something went wrong. Try again.',
  auth_error_conflict: 'That address cannot be registered.',
  auth_error_credentials: 'Incorrect email or password.',
  auth_error_not_verified: 'Confirm your address first.',
  auth_error_passwords_match: 'Passwords do not match.',

  // T129/T130/T134 — scan and report screens.
  scan_start_error: 'Could not start the scan. Try again.',
  progress_cancel: 'Cancel scan',
  progress_open_report: 'Open report',
  progress_running: 'Running',
  report_export: 'Export',
  report_reaudit: 'Re-audit',
  report_areas: 'Areas',
  report_summary: 'Executive summary',
  report_tab_all: 'All',
  report_copy_prompt: 'Copy fix prompt',
  report_copied: 'Copied',
} as const;

const ar: Record<keyof typeof en, string> = {
  promo: 'أول تدقيق مجاناً — ٥٠ رصيداً',
  nav_product: 'المنتج',
  nav_pricing: 'الأسعار',
  nav_docs: 'المستندات',
  nav_changelog: 'التحديثات',
  signin: 'تسجيل الدخول',
  start_free: 'ابدأ مجاناً',
  hero_lead: 'تظن أن موقعك جاهز؟',
  hero_accent: 'أثبت ذلك، ثم أطلقه.',
  hero_sub:
    'ندقّق الأداء والأمن والتصميم والاختبار والظهور في البحث — نقيس أولاً، ثم نشرح. بعد ذلك نتحقق من كل إصلاح حتى تصبح اللوحة خضراء بالكامل.',
  url_ph: 'موقعك.com',
  hero_cta: 'دقّق موقعي',
  stat_credits: 'رصيد مجاني، بدون بطاقة',
  stat_areas: 'مجالات',
  stat_recheck: 'أرصدة لكل إعادة تحقق',
  diff_eyebrow: 'الفرق',
  diff_h2: 'غيرنا يبيعك تقريراً.',
  diff_lead:
    'نحن نبيعك المسار من الأحمر إلى الأخضر، ونتحقق من كل خطوة. تتحول المشكلة إلى اللون الأخضر عندما ينجح الفحص، لا عندما تقول أنت ذلك.',
  diff_1t: 'القياس قبل الاستنتاج',
  diff_1d: 'كل ما يمكن قياسه نقيسه ولا نخمّنه. وكل نتيجة تُوضّح أيّهما كانت.',
  diff_2t: 'الأخضر يعني مُتحقَّقاً منه',
  diff_2d: 'إعادة التحقق المحدودة تكلّف ٣ أرصدة وثوانٍ. إما أن تنجح، أو تبقى المشكلة حمراء.',
  diff_3t: 'تدهور، لا انهيار',
  diff_3d: 'فشل أي قدرة يؤدي إلى تدهور مجالها فقط. ونخبرك بالضبط بما لم يُنفَّذ.',
  proof_note:
    'المجال المتدهور لا يُقرأ أبداً كنجاح. وإن لم نتمكّن من تنفيذ فحص، يذكر التقرير ذلك ولا تُحاسب عليه.',
  areas_eyebrow: 'خمسة مجالات',
  areas_h2: 'كل مجال يقدّم نتيجته باستقلال.',
  a_perf: 'الأداء',
  a_perf_d: 'مؤشرات الويب الأساسية، تركيب الحِزم، أنماط الطلبات',
  a_sec: 'الأمن',
  a_sec_d: 'الترويسات، TLS، فحوص OWASP، بيانات الاعتماد المكشوفة، ثغرات التبعيات',
  a_des: 'التصميم',
  a_des_d: 'التخطيط والتسلسل البصري والتباين، مقارنةً بهوية علامتك المعلنة',
  a_test: 'الاختبار',
  a_test_d: 'مسارات وظيفية تُنفَّذ في متصفح حقيقي',
  a_seo: 'الظهور في البحث',
  a_seo_d: 'البيانات الوصفية، قابلية الزحف، بنية المحتوى',
  areas_note:
    'المجالات الخمسة تكلّف ٩٥ منفردة مقابل ٨٠ مجتمعة. التغطية الكاملة هي دائماً أرخص طريق إلى التغطية الكاملة.',
  loop_eyebrow: 'حلقة الإصلاح',
  loop_h2: 'من الأحمر إلى الأخضر، فحصاً بعد فحص.',
  loop_1t: 'دقّق',
  loop_1d: 'أرسل رابطاً أو مستودعاً أو ملفاً مضغوطاً.',
  loop_2t: 'أصلِح',
  loop_2d: 'انسخ نصّ الإصلاح إلى مساعد البرمجة الذي تستخدمه.',
  loop_3t: 'أعد التحقق',
  loop_3d: '٣ أرصدة وثوانٍ. إما تنجح أو تبقى حمراء.',
  loop_4t: 'أطلِق',
  loop_4d: 'إعادة تدقيق كاملة وجديدة تعيد قراراً صريحاً بالموافقة أو الرفض.',
  cta_h2: 'خمسون رصيداً. بدون بطاقة.',
  cta_lead: 'تكفي لتدقيق مجالين أو ثلاثة من موقعك الحقيقي ورؤية نتائج حقيقية.',
  foot_tag: 'القياس قبل الاستنتاج. الأخضر يعني مُتحقَّقاً منه. ولا تُحاسب أبداً على أخطائنا.',
  foot_product: 'المنتج',
  foot_pricing: 'الأسعار',
  foot_company: 'الشركة',
  foot_dashboard: 'لوحة التحكم',
  foot_admin: 'وحدة المشغّل',
  foot_zero: 'صفر طلبات خارجية أثناء التشغيل',
  g_audits: 'التدقيقات',
  g_account: 'الحساب',
  n_scan: 'تدقيق جديد',
  n_progress: 'تدقيق مباشر',
  n_report: 'التقرير',
  n_fixes: 'الإصلاحات',
  n_readiness: 'الجهوزية',
  n_usage: 'الاستخدام',
  n_billing: 'الفواتير والخطط',
  n_profile: 'الملف الشخصي',
  credits_left: 'رصيد متبقٍ',
  top_up: 'إضافة رصيد',
  scan_eyebrow: 'تدقيق جديد',
  scan_title: 'ما الذي ندقّقه؟',
  tab_url: 'رابط',
  tab_repo: 'مستودع',
  tab_archive: 'ملف مضغوط',
  areas_label: 'المجالات',
  quote: 'التسعيرة',
  credits: 'رصيد',
  quote_bundled: 'مجتمعة — أقل بـ ١٥ رصيداً من المجموع المنفرد.',
  quote_note:
    'لا يُخصم شيء حتى توافق على هذه التسعيرة. وإذا فشلت المنصّة في منتصف التدقيق، تعود الأرصدة.',
  accept_run: 'موافقة وتشغيل',
  drop_archive: 'أفلِت ملف .zip أو .tar.gz',
  drop_note: 'يُتحقَّق منه قبل الاستخراج، ويُحذف عند انتهاء التدقيق.',
  theme_dark: 'داكن',
  theme_light: 'فاتح',

  auth_signin_title: 'تسجيل الدخول',
  auth_signin_lead: 'تدقيقاتك ولوحة الإصلاحات في مكانها الذي تركتها فيه.',
  auth_signin_foot_lead: 'ليس لديك حساب؟',
  auth_signin_foot_link: 'ابدأ مجاناً',
  auth_signin_foot_tail: '— ٥٠ رصيداً، بدون بطاقة.',
  auth_email: 'البريد الإلكتروني',
  auth_password: 'كلمة المرور',
  auth_forgot_link: 'نسيت؟',
  auth_signin_submit: 'تسجيل الدخول',
  auth_or: 'أو',
  auth_github: 'المتابعة عبر GitHub',
  auth_register_title: 'إنشاء حساب',
  auth_register_lead: 'خمسون رصيداً، بدون بطاقة. تكفي لتدقيق مجالين أو ثلاثة من موقعك الحقيقي.',
  auth_register_foot_lead: 'لديك حساب بالفعل؟',
  auth_register_foot_link: 'تسجيل الدخول',
  auth_name: 'الاسم',
  auth_work_email: 'البريد الإلكتروني للعمل',
  auth_password_hint: 'اثنا عشر حرفاً على الأقل',
  auth_register_note: 'نرسل رسالة تحقق واحدة. لا يمكنك تسجيل الدخول حتى يتم تأكيدها.',
  auth_register_submit: 'إنشاء حساب',
  auth_verify_title: 'تحقّق من بريدك الإلكتروني',
  auth_verify_lead: 'أرسلنا رابط تحقق إلى {email}. تنتهي صلاحيته خلال ٢٤ ساعة.',
  auth_verify_foot_lead: 'العنوان غير صحيح؟',
  auth_verify_foot_link: 'ابدأ من جديد',
  auth_verify_resend: 'إعادة إرسال الرسالة',
  auth_verify_confirmed_title: 'تم تأكيد العنوان',
  auth_verify_confirmed_lead: 'يمكنك تسجيل الدخول الآن.',
  auth_verify_confirmed_submit: 'تسجيل الدخول',
  auth_verify_invalid_title: 'هذا الرابط لم يعد صالحاً',
  auth_verify_invalid_lead: 'إما أنه استُخدم من قبل أو انتهت صلاحيته.',
  auth_forgot_title: 'إعادة تعيين كلمة المرور',
  auth_forgot_lead: 'أدخل العنوان المسجّل في حسابك وسنرسل رابطاً للاستخدام مرة واحدة.',
  auth_forgot_foot_link: 'العودة لتسجيل الدخول',
  auth_forgot_submit: 'إرسال رابط إعادة التعيين',
  auth_forgot_sent_lead: 'إذا كان لهذا العنوان حساب، فرابط إعادة التعيين في طريقه إليه.',
  auth_reset_title: 'اختر كلمة مرور جديدة',
  auth_reset_lead: 'هذا الرابط للاستخدام مرة واحدة. تسجيل الدخول مجدداً يلغي كل الجلسات الأخرى.',
  auth_reset_foot_link: 'العودة لتسجيل الدخول',
  auth_new_password: 'كلمة المرور الجديدة',
  auth_confirm_password: 'تأكيد كلمة المرور الجديدة',
  auth_repeat_it: 'كرّرها',
  auth_min_chars: 'اثنا عشر حرفاً على الأقل',
  auth_reset_submit: 'تعيين كلمة المرور وتسجيل الدخول',
  auth_reset_done_title: 'تم تغيير كلمة المرور',
  auth_reset_done_lead: 'تم تسجيل الخروج من كل الجلسات. سجّل الدخول بكلمة المرور الجديدة.',
  auth_error_generic: 'حدث خطأ ما. حاول مرة أخرى.',
  auth_error_conflict: 'لا يمكن تسجيل هذا العنوان.',
  auth_error_credentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
  auth_error_not_verified: 'أكّد عنوانك أولاً.',
  auth_error_passwords_match: 'كلمتا المرور غير متطابقتين.',

  scan_start_error: 'تعذّر بدء التدقيق. حاول مرة أخرى.',
  progress_cancel: 'إلغاء التدقيق',
  progress_open_report: 'فتح التقرير',
  progress_running: 'قيد التنفيذ',
  report_export: 'تصدير',
  report_reaudit: 'إعادة التدقيق',
  report_areas: 'المجالات',
  report_summary: 'الملخص التنفيذي',
  report_tab_all: 'الكل',
  report_copy_prompt: 'نسخ نص الإصلاح',
  report_copied: 'تم النسخ',
};

export type StringKey = keyof typeof en;

export const WA_STRINGS: Record<Lang, Record<StringKey, string>> = { en, ar };
